services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app-net

  ocr-service:
    build:
      context: ./PyTesseract
      dockerfile: Dockerfile
    container_name: ocr-service
    depends_on:
      - qdrant
    volumes:
      - ./PyTesseract:/app
      - ./PythonScript:/PythonScript
    networks:
      - app-net
    environment:
      QDRANT_URL: "http://qdrant:6333"

volumes:
  qdrant_data:

networks:
  app-net:
